/* ========================= HELPERS ========================= */
const $=id=>document.getElementById(id);
const fmt=n=>(+n).toLocaleString('es-CO');
const money=n=>'$'+(+n).toLocaleString('es-CO');
const now=()=>{const d=new Date();return d.getDate()+'/'+(d.getMonth()+1)+' '+d.getHours()+':'+String(d.getMinutes()).padStart(2,'0')};
const prods=()=>DB.productos;
const getProd=sku=>DB.productos.find(p=>p.sku===sku);
const getProv=id=>DB.proveedores.find(p=>p.id===id)||{n:'—'};
const stockTotal=sku=>Object.values(DB.stock).reduce((s,b)=>s+(b[sku]||0),0);
const stockBodega=(bg,sku)=>(DB.stock[bg]&&DB.stock[bg][sku])||0;
const bestBodega=sku=>{let best=null,max=-1;DB.bodegas.forEach(b=>{const v=stockBodega(b.id,sku);if(v>max){max=v;best=b.id}});return best};
const bodegaColor=id=>{const b=DB.bodegas.find(x=>x.id===id);return b?b.estado:'verde'};
const ocValor=oc=>oc.items.reduce((s,i)=>s+i.cant*i.precio,0);
const pedEstLabel=e=>({pendiente:'Pendiente',asignado:'Asignado',resagado:'Rezago por Stock',parcial_asignado:'Parcial (Asignado)',parcial_resagado:'Parcial (Rezago)',despachado:'Despachado Total'})[e]||e;
const pedEstBadge=e=>({pendiente:'bs',asignado:'bb',resagado:'by',parcial_asignado:'bi',parcial_resagado:'by',despachado:'bg'})[e]||'bs';
const compEstLabel=e=>({borrador:'Borrador',transito:'En tránsito',recibida:'Recibida sin reclamar',reclamada:'Reclamada'})[e]||e;
const compEstBadge=e=>({borrador:'bs',transito:'bb',recibida:'by',reclamada:'bg'})[e]||'bs';
const trEstLabel=e=>({solicitada:'Solicitada',autorizada:'Autorizada',despachada:'Despachada',recibida:'Recibida'})[e]||e;
const getCliente=id=>DB.clientes.find(c=>c.id===id)||{n:'—'};
const fvEstLabel=e=>({emitida:'Emitida',anulada:'Anulada',pagada:'Pagada'})[e]||e;
const fvEstBadge=e=>({emitida:'bb',anulada:'br',pagada:'bg'})[e]||'bs';
const fcEstLabel=e=>({recibida:'Recibida',en_disputa:'En Disputa',pagada:'Pagada'})[e]||e;
const fcEstBadge=e=>({recibida:'bb',en_disputa:'by',pagada:'bg'})[e]||'bs';
const ndTipoLabel=e=>({credito:'Crédito',debito:'Débito'})[e]||e;
const ctEstLabel=e=>({borrador:'Borrador',enviada:'Enviada',aceptada:'Aceptada',rechazada:'Rechazada',vencida:'Vencida'})[e]||e;
const ctEstBadge=e=>({borrador:'bs',enviada:'bb',aceptada:'bg',rechazada:'br',vencida:'by'})[e]||'bs';
const occEstLabel=e=>({pendiente:'Pendiente',aprobada:'Aprobada',remisionada:'Remisionada',cancelada:'Cancelada'})[e]||e;
const occEstBadge=e=>({pendiente:'bs',aprobada:'bb',remisionada:'bg',cancelada:'br'})[e]||'bs';
const rmEstLabel=e=>({pendiente:'Pendiente',en_proceso:'En Proceso',despachada:'Despachada',entregada:'Entregada'})[e]||e;
const rmEstBadge=e=>({pendiente:'bs',en_proceso:'bb',despachada:'by',entregada:'bg'})[e]||'bs';
const getPrefijo=tipo=>DB.config.prefijos.find(p=>p.tipo===tipo&&p.activo);
const nextConsecutivo=tipo=>{const p=getPrefijo(tipo);if(!p)return null;const n=p.prefijo+String(p.consecutivo_actual).padStart(4,'0');p.consecutivo_actual++;saveDB();return n};
const getCat=id=>DB.config.categorias.find(c=>c.id===id);
const getSubcat=id=>DB.config.subcategorias.find(s=>s.id===id);
const getUnidad=id=>DB.config.unidades.find(u=>u.id===id);
const getPuntoVenta=id=>DB.config.puntos_venta.find(p=>p.id===id);
const getCategoriasActivas=()=>DB.config.categorias.filter(c=>c.activo);
const getSubcatsByCat=catId=>DB.config.subcategorias.filter(s=>s.categoria_id===catId&&s.activo);
const getGrupoConversion=id=>DB.config.grupos_conversion.find(g=>g.id===id);
const getProductoGrupo=prod=>prod.grupo_conversion_id?getGrupoConversion(prod.grupo_conversion_id):null;
const convertirAUnidadBase=(grupoId,unidadId,cantidad)=>{
  const g=getGrupoConversion(grupoId);
  if(!g)return cantidad;
  const u=g.unidades.find(x=>x.unidad_id===unidadId);
  return u?cantidad/u.factor:cantidad;
};